import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Link } from "react-router-dom";

export default function TermsOfService() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      
      <main className="flex-1 py-12">
        <div className="container max-w-4xl">
          <article className="prose prose-invert max-w-none">
            <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
            <p className="text-muted-foreground mb-8">Last updated: January 31, 2026</p>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using SC-Workflow4AI (the "Service") at flow-scribe-wise.lovable.app, you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground">
                SC-Workflow4AI is an AI-powered workflow generation platform that creates production-grade n8n and Node-RED workflows. The Service uses artificial intelligence to generate workflow specifications based on user inputs and provides export-ready JSON files for integration with supported platforms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts</h2>
              <p className="text-muted-foreground mb-4">
                When you create an account, you must provide accurate and complete information. You are responsible for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized access</li>
                <li>Ensuring your account information remains accurate and up-to-date</li>
              </ul>
              <p className="text-muted-foreground mt-4">
                We reserve the right to suspend or terminate accounts that violate these Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. Acceptable Use</h2>
              <p className="text-muted-foreground mb-4">You agree not to use the Service to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe upon the intellectual property rights of others</li>
                <li>Generate malicious, harmful, or illegal workflows</li>
                <li>Attempt to gain unauthorized access to systems or networks</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Transmit viruses, malware, or other malicious code</li>
                <li>Engage in automated data collection without permission</li>
                <li>Impersonate others or misrepresent your affiliation</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Intellectual Property</h2>
              
              <h3 className="text-xl font-medium text-foreground mb-3">5.1 Our Content</h3>
              <p className="text-muted-foreground mb-4">
                The Service, including its original content, features, and functionality, is owned by SupportCALL and is protected by international copyright, trademark, and other intellectual property laws.
              </p>

              <h3 className="text-xl font-medium text-foreground mb-3">5.2 Your Content</h3>
              <p className="text-muted-foreground mb-4">
                You retain ownership of any content you submit to the Service. By using the Service, you grant us a limited license to process your inputs solely for the purpose of generating workflows.
              </p>

              <h3 className="text-xl font-medium text-foreground mb-3">5.3 Generated Workflows</h3>
              <p className="text-muted-foreground">
                Workflows generated by the Service are provided for your use. You may use, modify, and deploy generated workflows in accordance with these Terms. However, we make no warranty regarding the generated content (see Section 8).
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Credits and Payments</h2>
              <p className="text-muted-foreground mb-4">
                Access to certain features may require credits or payment. By using paid features:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Credits are non-refundable unless otherwise stated</li>
                <li>Unused credits may expire as specified in your account</li>
                <li>Pricing is subject to change with reasonable notice</li>
                <li>You are responsible for any applicable taxes</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. Third-Party Integrations</h2>
              <p className="text-muted-foreground">
                The Service generates workflows for third-party platforms including n8n and Node-RED. Your use of these platforms is subject to their respective terms and conditions. We are not responsible for the operation, availability, or policies of third-party platforms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground mb-4">
                <strong>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</strong>
              </p>
              <p className="text-muted-foreground mb-4">
                We do not warrant that:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>The Service will meet your specific requirements</li>
                <li>Generated workflows will be error-free or suitable for production without review</li>
                <li>The Service will be uninterrupted, secure, or error-free</li>
                <li>Results obtained will be accurate or reliable</li>
              </ul>
              <p className="text-muted-foreground mt-4 p-4 bg-muted/30 rounded-lg">
                <strong>Important:</strong> Generated workflows should be reviewed by qualified professionals before deployment in production environments. Consult with your ICT professional regarding network security and workflow implementation. Use at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SUPPORTCALL, ITS AFFILIATES, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING FROM YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">10. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify and hold harmless SupportCALL and its affiliates from any claims, damages, losses, or expenses arising from your use of the Service, violation of these Terms, or infringement of any rights of third parties.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">11. Service Modifications</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">12. Termination</h2>
              <p className="text-muted-foreground">
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including breach of these Terms. Upon termination, your right to use the Service will cease immediately.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">13. Governing Law</h2>
              <p className="text-muted-foreground">
                These Terms shall be governed by and construed in accordance with the laws of Australia, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Australia.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">14. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting to this page. Your continued use of the Service after changes constitutes acceptance of the modified Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">15. Severability</h2>
              <p className="text-muted-foreground">
                If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">16. Contact Information</h2>
              <p className="text-muted-foreground mb-4">
                For questions about these Terms, please contact:
              </p>
              <p className="text-muted-foreground">
                <strong>SupportCALL</strong><br />
                Website: <a href="https://www.supportcall.com.au/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">www.supportcall.com.au</a>
              </p>
            </section>

            <div className="mt-12 pt-8 border-t border-border">
              <Link to="/" className="text-primary hover:underline">
                ← Return to Home
              </Link>
            </div>
          </article>
        </div>
      </main>

      <Footer />
    </div>
  );
}
